### ISSUE TITLE
too many hard choices

### ISSUE THREAD

**Issue by Colinwielga** [Colinwielga/Wanderer-Cordova#16]

**Comment by DeepwaterCreations** [comment]
It would be nice if there were a way to make sure hard choices come up only in situations where it's easy/makes sense to have a hard choice. Or at least situations where that's more likely to be true.

**Comment by Colinwielga** [comment]
yeah, like a check box "allow hard choice".

I am a little worried about adding too many steps for the DM. I am alright with adding this one since it is optional.

**Comment by DeepwaterCreations** [comment]
On the other hand, I think it's easy to first think there's no hard choice, then if you think about it for a second or two, it turns out there's a really good one. 
And if there's a checkbox, you have to judge whether there's a hard choice or not every time, before you even do the roll, but then it might not matter. If it were me, I'd probably be lazy and just leave it at the default constantly.
Dunno.
What if it gave a couple options? Like, 8-10: Hard choice or something something. And then if the GM can't think of a good hard choice, they can fall back on the something something.

**Comment by DeepwaterCreations** [comment]
This is all increasingly nothing to do with the actual issue, isn't it. 
Sorry - I'm trying to jobhunt right now, but my brain would much rather be distracted and think about roleplaying games.

**Comment by Colinwielga** [comment]
It could be "hard choice or mixed result" with the DM deciding after the player has played there card. Hard choice and mixed result already occupy the same space (between pass and failure) and never coexist.

Or, It could be "hard choice or failure" with the DM deciding when they read the list to the player.

I just had an unrelated ideas: a new outcome "on second thought you decide not to do it". Makes more sense in the Chris game.

I my brain WAS happy thinking about work...

**Comment by DeepwaterCreations** [comment]
At first, I didn't think I liked "on second thought you decide not to do it", but maybe that's okay because you still basically get to choose as a player, with your cards. It's not something that's forced on you and it's not just a boring nothing-happens outcome, it's an opportunity as a player to un-commit yourself at the cost of a card.
